# Generated by Django 4.0.6 on 2022-07-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cabo_created_cabo_updated_equipe_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='hierarquia',
            field=models.CharField(choices=[('coordenador', 'Coordenador'), ('líder', 'Líder'), ('cabo', 'Cabo Eleitoral'), ('eleitor', 'Eleitor')], max_length=15, null=True),
        ),
    ]
