# Generated by Django 4.0.6 on 2022-07-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pessoa_hierarquia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='hierarquia',
        ),
        migrations.AlterField(
            model_name='cabo',
            name='cabo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.pessoa'),
        ),
        migrations.AlterField(
            model_name='cabo',
            name='líder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.líder'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.pessoa'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.grupo'),
        ),
        migrations.AlterField(
            model_name='líder',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.equipe'),
        ),
        migrations.AlterField(
            model_name='líder',
            name='líder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.pessoa'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='cabo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.cabo'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='eleitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.pessoa'),
        ),
    ]
